# Generated by Django 4.2.2 on 2024-05-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(help_text='Введите свою страну', max_length=255, verbose_name='Страна'),
        ),
    ]
